version: 0.2

phases:
  build:
    commands:
      - cd myapp-backend
      - mvn clean package -DskipTests

artifacts:
  files:
    - myapp-backend/target/app.jar
    - myapp-backend/Procfile
  discard-paths: yes
