version: 0.2

phases:
  build:
    commands:
      - cd myapp-backend
      - mvn clean package -DskipTests
      - cp target/app.jar ../app.jar
      - cp Procfile ../Procfile

artifacts:
  files:
    - app.jar
    - Procfile
