server:
  port: ${SERVER_PORT:5000}

spring:
  application:
    name: GST_INVOICE

  profiles:
    active: ${PROFILE:dev}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  jpa:
    show-sql: true

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

host_url: ${VERIFY_EMAIL_HOST}

database-config:
  host: ${SPRING_DATASOURCE_URL}    # full JDBC URL from EB env
  port: 5432
  database: invoice
  username: ${SPRING_DATASOURCE_USERNAME}
  password: ${SPRING_DATASOURCE_PASSWORD}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      data-source-properties:
        sslmode: ${SPRING_DATASOURCE_SSLMODE:verify-full}
        sslrootcert: ${SPRING_DATASOURCE_SSLROOTCERT:/var/app/current/global-bundle.pem}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

backup:
  pgDumpPath: ${pgDumpPath}
  backupFilePath: ${backupFilePath}
