server:
  port: ${SERVER_PORT:5000}

spring:
  application:
    name: GST_INVOICE
  profiles:
    active: ${PROFILE:dev}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:default}
            client-secret: ${GOOGLE_CLIENT_SECRET:default}
          github:
            client-id: ${GITHUB_CLIENT_ID:default}
            client-secret: ${GITHUB_CLIENT_SECRET:default}
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID:default}
            client-secret: ${FACEBOOK_CLIENT_SECRET:default}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  mail:
    host: ${EMAIL_HOST:smtp.gmail.com}
    port: ${EMAIL_PORT:587}
    username: ${EMAIL_ID:default}
    password: ${EMAIL_PASSWORD:default}
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  datasource:
    url: jdbc:postgresql://${host}:${port}/${database}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

host_url: ${VERIFY_EMAIL_HOST:http://localhost:5000}

database-config:
  host: ${host}
  port: ${port}
  database: ${database:invoice}
  username: ${spring.datasource.username:postgres}
  password: ${spring.datasource.password}

backup:
  pgDumpPath: ${pgDumpPath:/usr/bin/pg_dump}
  backupFilePath: ${backupFilePath:/tmp/backup}
