server:
  port: ${SERVER_PORT:5000}
spring:
  application:
    name: GST_INVOICE
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/invoice}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  mail:
    host: ${EMAIL_HOST:smtp.gmail.com}
    port: ${EMAIL_PORT:587}
    username: ${EMAIL_ID:default}
    password: ${EMAIL_PASSWORD:default}
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:default}
            client-secret: ${GOOGLE_CLIENT_SECRET:default}
          github:
            client-id: ${GITHUB_CLIENT_ID:default}
            client-secret: ${GITHUB_CLIENT_SECRET:default}
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID:default}
            client-secret: ${FACEBOOK_CLIENT_SECRET:default}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

host_url: ${VERIFY_EMAIL_HOST:http://localhost:5000}
backup:
  pgDumpPath: ${PG_DUMP_PATH:/usr/bin/pg_dump}
  backupFilePath: ${BACKUP_FILE_PATH:/tmp/backup}
